services:
  supermercado-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=supermercado;user=root;password=rootpassword"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
      - db
    networks:
      - supermercado-network
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - supermercado-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supermercado
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  supermercado-network:
    driver: bridge